#!/usr/bin/lua
--Faito,2015,NamPham
--validate IP address

local params = {...}

function isIpAddress(ip)
  if not ip then return 0 end
  local a,b,c,d=ip:match("^(%d%d?%d?)%.(%d%d?%d?)%.(%d%d?%d?)%.(%d%d?%d?)$")
  a=tonumber(a)
  b=tonumber(b)
  c=tonumber(c)
  d=tonumber(d)
  if not a or not b or not c or not d then return 0 end
  if a<0 or 255<a then return 0 end
  if b<0 or 255<b then return 0 end
  if c<0 or 255<c then return 0 end
  if d<0 or 255<d then return 0 end
  return 1
end

print(isIpAddress(params[1]))
